"""initial

Revision ID: b4a103dca31a
Revises: 
Create Date: 2024-03-09 21:12:34.445234

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4a103dca31a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bet_coef", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("bet_deadline", sa.DateTime(), nullable=False),
        sa.Column(
            "status_event",
            sa.Enum(
                "unfinished", "team_1_won", "team_2_won", native_enum=False
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events")
    # ### end Alembic commands ###
